service: EVE
frameworkVersion: "3"

custom:
  BUCKET: "EVE"
  ASSESSKEY: "AKIAYSMBM5OAH2OGE26Q"
  SCRETKEY: "lPMm1bvz3jdh8fBRNy3Th5nZOEL7VkwV48X/uCrN"
  region: "us-east-2"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  timeout: 300
  memorySize: 1024

  environment:
    ASSESSKEY: ${self:custom.ASSESSKEY}
    SCRETKEY: ${self:custom.SCRETKEY}
    region: ${self:custom.region}

functions:
  api:
    handler: index.api
    events:
      - httpApi: "*"