service: EVE
frameworkVersion: "3"

custom:
  BUCKET: "EVE"
  region: "us-east-2"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  timeout: 300
  memorySize: 1024

  environment:
    region: ${self:custom.region}

functions:
  api:
    handler: index.api
    events:
      - httpApi: "*"